### ISSUE TITLE
Apps reports succesful upload, but no files appears on server

### ISSUE THREAD

**Issue by fliker09** [PhotoBackup/server-php#5]
Debian Wheezy + nginx + PB server-php. No error in any place reported, photos gets uploaded, but I don't see any actual files to appear on the server side. How can I debug this situation?

**Comment by Zegnat** [comment]
That’s odd. I really thought I covered all edge-cases.

> How can I debug this situation?

Maybe check the nginx access logs. I do not have a lot of experience with nginx administration. This  minimal implementation does not offer any debugging options and you would have to write it yourself.

What version of PHP are you running?

I should probably add a logger into this. Probably something [PSR-3](http://www.php-fig.org/psr/psr-3/) compatible. But no clue when I will have time to do that.

**Comment by fliker09** [comment]
nginx logs are clean.... nothing suspicious. PHP 5.6.19. Yeah, would be glad to get any ability to find out what is going on...

**Comment by Zegnat** [comment]
> nginx logs are clean.... nothing suspicious. PHP 5.6.19.

That should all be fine. How annoying. Now I am annoyed. Will probably open a branch tomorrow and just put in a copy of the current server implementation but with log file writing. I’ll mention you when it is up so you can give it a test.

**Comment by Zegnat** [comment]
@fliker09: I have just published a logging branch. Could you check it out and see what its logging turns up? It should be making a log entry at every step.

https://github.com/PhotoBackup/server-php/tree/temp-logging

**Comment by fliker09** [comment]
Thank you for your efforts! I didn't get the log, but it was a good hint that something is wrong with permissions (which I thought are totally OK). And I finally found it - problem was on 2 levels up! Photos are happily uploaded :)

**Comment by Zegnat** [comment]
That's weird. If the target folder has permission issues that should really be picked up by [my over-the-top checking](https://github.com/PhotoBackup/server-php/blob/temp-logging/index.php#L125-L141) and the server should respond with an error to the client. Maybe that is a client bug. Might require more testing, but glad you figured it out!

**Comment by fliker09** [comment]
It's all logical - log couldn't be written because... no permission! But yeah, it was unpleasant that it couldn't be caught by app
